

export const authConstants={
    SIGNIN_REQUEST:"SIGNIN_REQUEST",
    SIGNIN_SUCCESS:"SIGNIN_SUCCESS",
    SIGNUP_REQUEST:"SIGNUP_REQUEST",
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    REGISTER_REQUEST:'REGISTER_REQUEST',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    APPLY_REQUEST:"APPLY_REQUEST",
    APPLY_SUCCESS:"APPLY_SUCCESS",
    APPLIED_ALREADY:"APPLIED_ALREADY",
    UPDATE_REQUEST:"UPDATE_REQUEST",
    UPDATE_SUCCESS:"UPDATE_SUCCESS",
    APPLIED_REQUEST:"APPLIED_REQUEST",
    GET_REQUEST:"GET_REQUEST",
    GET_SUCCESS:"GET_SUCCESS",
}